name: synthpls
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  drift: ^2.21.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.7.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  provider: ^6.1.2
  sqlite3_flutter_libs: ^0.5.26
  flutter_svg: ^2.0.14
  xml: ^6.5.0
  wolt_modal_sheet: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.0.0
  build_runner: ^2.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/chimgio.db
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/market.png
    - assets/images/blog/0.png
    - assets/images/characters/0.png
